GET http://localhost:3001/goals HTTP/1.1
Content-Type: application/json

###!SECTION

POST http://localhost:3001/goals HTTP/1.1
Content-Type: application/json

{
    "goalName": "read"
}

PUT http://localhost:3001/goals/1 HTTP/1.1
Content-Type: application/json

{
    "id": 
}